### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by arblake** [CCurl/Q4#2]
make has problems compiling:
adrian@adrian-hp:~/Q4$ ./make
rm: cannot remove 'Q4': No such file or directory
In file included from /usr/include/c++/11/stdlib.h:36,
                 from Q4.cpp:6:
/usr/include/c++/11/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
   41 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Using clang works but with this: 
adrian@adrian-hp:~/Q4$ clang -O3 -oQ4 -lm -D_LINUX Q4.cpp
Q4.cpp:78:39: warning: use of unary operator that may be intended as compound assignment (-=)
            else if (t1 == 'u') { lsp =- 3; }
                                      ^~
1 warning generated.

**Comment by arblake** [comment]
fixed by doing this : sudo apt-get install gcc-multilib g++-multilib

**Comment by CCurl** [comment]
Thanks, and sorry for not noticing this earlier.
